"""Pipeline orchestration example.

Demonstrates a supervised multi-step pipeline: search → summarize → write.
Each step is fully supervised (timeouts, budgets, audit, PII redaction).

Run:
    python examples/pipeline.py
"""

import asyncio

from clawboss import MemoryStore, SessionManager
from clawboss.pipeline import Pipeline

# -- Simulated tools --


async def web_search(query: str = "") -> str:
    """Pretend to search the web."""
    return f"Found 3 results for '{query}': result A, result B, result C"


async def summarize(input: str = "") -> str:
    """Pretend to summarize with an LLM."""
    return f"Summary: {input[:80]}..."


async def write_report(input: str = "", title: str = "Report") -> str:
    """Pretend to write a report."""
    return f"# {title}\n\n{input}\n\n---\nGenerated by Clawboss pipeline."


async def main() -> None:
    store = MemoryStore()
    mgr = SessionManager(store)

    # Build and run a pipeline
    print("=== Running pipeline ===\n")
    result = await (
        Pipeline(
            mgr,
            agent_id="researcher",
            policy_dict={
                "max_iterations": 10,
                "tool_timeout": 30,
                "token_budget": 50000,
            },
        )
        .add_step("web_search", web_search, query="quantum computing 2026")
        .add_step("summarize", summarize)
        .add_step("write_report", write_report, title="Quantum Computing Report")
        .run()
    )

    # Show results
    print(f"Completed: {result.completed}")
    print(f"Steps run: {len(result.steps)}")
    print(f"Total duration: {result.total_duration_ms}ms")
    print()

    for step in result.steps:
        status = "OK" if step.result.succeeded else "FAILED"
        print(f"  Step {step.step_index + 1}: {step.name} [{status}] ({step.result.duration_ms}ms)")

    print("\n=== Final output ===\n")
    print(result.final_output)

    # Check observability
    print("\n=== Metrics ===\n")
    for tool_name, metrics in mgr.observer.all_tools_summary().items():
        print(f"  {tool_name}: {metrics['calls']} calls, avg {metrics['avg_latency_ms']}ms")


if __name__ == "__main__":
    asyncio.run(main())
